name: ml_training
channels:
  - defaults
dependencies:
  - python=3.10
  - torchaudio
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - transformers
  - accelerate
  - scipy
  - nltk
  - scikit-learn
  - sentencepiece
  - protobuf
  - wandb
  - absl-py
